### ISSUE TITLE
Load testing Willow

### ISSUE THREAD

**Issue by Nimphal** [CottageLabs/willow#101]
Use demo created in #100 to establish some base load stats.

**Comment by emanuil-tolev** [comment]
Suggested during meeting:

1. define common scenarios of use, so we have some user sessions to simulate. Probably with @anusharanganathan .
2. try to get as much monitoring as feasible. Docker is supposed to enable a fair bit of monitoring with cgroups, but setting this up properly could be time-consuming. Hopefully there's a Docker monitoring tool that will enable this to happen in a few hours.
3. load test demo app.
4. upgrade demo server, load test again.
5. upgrade demo server, load test again.

If we watch the resource use during load tests, we will get an idea of the upper bound (how many concurrent heavy users we support). If we can pull off the resource monitoring, especially CPU, RAM, IOPS, then we will also learn about what our bottlenecks are.

**Comment by Nimphal** [comment]
Acceptance criteria for this issue:

- [ ] Stats for multiple sessions hitting the home page
- [ ] Stats for multiple sessions hitting the public search interface

**Comment by richard-jones** [comment]
The deadline for some form of load testing information for an upcoming bid is 21st April.
