### ISSUE TITLE
Solr crashes when reindexing fedora

### ISSUE THREAD

**Issue by Nimphal** [CottageLabs/willow#113]

**Comment by martyn-w** [comment]
Related to reindexing, see: https://github.com/projecthydra/sufia/wiki/Backup-and-Restoration

**Comment by martyn-w** [comment]
This was caused by the spell-check/suggestion module in the Solr index configuration; now disabled in branch https://github.com/CottageLabs/willow/tree/fix_solr_schema

**Comment by martyn-w** [comment]
Cf. https://github.com/CottageLabs/willow/pull/128#discussion_r112749213

**Comment by martyn-w** [comment]
Resolved in https://github.com/CottageLabs/willow/pull/129

**Comment by Nimphal** [comment]
Perfect, closing :)
