### ISSUE TITLE
Point willow.cottagelabs.com to the new demo

### ISSUE THREAD

**Issue by Nimphal** [CottageLabs/willow#116]
Depends on clearing out #115 #71 #114 ~~#105~~ #104

**Comment by Nimphal** [comment]
#105 is not posing a problem right now as we have not generated default admin sets in the demo.

**Comment by Nimphal** [comment]
All of the issues that this depends on have been cleared, @emanuil-tolev could we proceed with this? If yes, I will move this into coming sprint.

And could we also acquire an SSL certificate for the demo once the domain is repointed?

**Comment by emanuil-tolev** [comment]
> And could we also acquire an SSL certificate for the demo once the domain is repointed?

from today's meeting, yes

**Comment by emanuil-tolev** [comment]
new set of tasks to finish issue:

- repoint domain
- ssl by letsencrypt
- bring app down (incl volumes) and back up

**Comment by emanuil-tolev** [comment]
@Nimphal I've repointed the domain. I'd rather have a new issue for the SSL, since I suspect the way to deploy letsencrypt in a dockerised app is not quite the same as usual (besides doing it directly on the host server).

**Comment by emanuil-tolev** [comment]
I'm leaving creating the issue to you so it's in the right sprint so I know the deadline ;)

**Comment by Nimphal** [comment]
Have created #137 to follow work on the SSL certificate, closing this one.
