### ISSUE TITLE
Hosting costing

### ISSUE THREAD

**Issue by emanuil-tolev** [CottageLabs/willow#120]
Establish a typical monthly cost formula based on a few factors:

- amount of data to host
- bandwidth required per month
- number of concurrent users
- recovery time objective
- recovery point objective

Really this depends on how well our software stack handles those amounts of data, so #101 Load Testing will probably help inform this. We might have to guess a bit until we have more loading test data. I'll send suggestions around by email and record the consensus here.

**Comment by emanuil-tolev** [comment]
Not quite formula, but Herefordshire bid has relevant comments. Also sent around an estimate of actual hardware, first one we've ever done ;).

**Comment by Nimphal** [comment]
Is there something else that needs to be added to this issue? Perhaps an anonymised summary of the comments in the bid?

**Comment by emanuil-tolev** [comment]
> Perhaps an anonymised summary of the comments in the bid?

I don't think we need to put results in the issue, so long as results are written down somewhere sensible.

> Is there something else that needs to be added to this issue?

There is one extra thing that needs to be determined that I can't write here - over email.
