### ISSUE TITLE
Dataset model enhancements 

### ISSUE THREAD

**Issue by Nimphal** [CottageLabs/willow#139]
Make sure the Dataset model has all fields from Datacite metadata kernel http://schema.datacite.org/meta/kernel-4.0/doc/DataCite-MetadataKernel_v4.0.pdf

**Comment by anusharanganathan** [comment]
This is done. It is covered by https://github.com/CottageLabs/willow/pull/161, https://github.com/CottageLabs/willow/pull/172 and https://github.com/CottageLabs/willow/issues/151

**Comment by Nimphal** [comment]
Brilliant, closing.
