### ISSUE TITLE
Approach for communication with a message gateway

### ISSUE THREAD

**Issue by Nimphal** [CottageLabs/willow#152]
How can we enable Willow to broadcast CRUD operations messages to a configurable message gateway?

**Comment by martyn-w** [comment]
I think one solution is to use the ActiveSupport::Notifications built into Rails: http://guides.rubyonrails.org/active_support_instrumentation.html

**Comment by Nimphal** [comment]
I believe we are happy to use `ActiveSupport::Notifications` . If so, I will close this issue and create a new for initial implementation.

**Comment by martyn-w** [comment]
To confirm, I have a simple prototype generating console messages using the ActiveSupport::Notifications library
