### ISSUE TITLE
Create an administrative set and bind the one-step mediated deposit workflow for demo

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/willow#175]
on the branch feature/demo_seed_data please could someone:

1. Add the creation of a basic administrative set
2. Bind that administrative set to the one_step_mediated_deposit_workflow.yml workflow/config
3. Add the workflow user (see the demo.json seed file) to that admin set/workflow

If this can be done with configuration in demo.json, so that later we can change it/extend it as needed that would be good.

This is required in order to provide the demo at RDN on 27th June.

**Comment by martyn-w** [comment]
now complete
