### ISSUE TITLE
Changes to the way Willow runs on AWS

### ISSUE THREAD

**Issue by Nimphal** [CottageLabs/willow#182]
- [x] get Willow running on ECS
- [ ] replace container postgres with RDS Postgress -maintain a separate docker-compose.yml or create a new override, like docker-compose.jiscrdss.override.yml and add instructions on how to use i
- [ ] run Willow behind an ELB
- [ ] provide SSL

**Comment by emanuil-tolev** [comment]
> - [x] get Willow running on ECS

:muscle: !

Added

> - [ ] provide SSL

That's gonna happen via AWS key management and Letsencrypt.
