### ISSUE TITLE
Arkivum integration

### ISSUE THREAD

**Issue by Nimphal** [CottageLabs/willow#20]
Investigate what it would take to integrate Willow with Arkivum.

**Comment by martyn-w** [comment]
Arkivum is a commercial product ([originally developed in the UK](https://www.theregister.co.uk/2016/03/24/arkivum_archive_as_a_service/)) to manage the archival and preservation of digital assets.

It provides integrations in the form of:
* [Common Internet File System (CIFS)](https://technet.microsoft.com/en-us/library/cc939973.aspx) network shares which are accessible to Windows, Linux and Mac, allowing files to be uploaded and retrieved
* ReST API to get metadata, checksums and replication status of objects
* Arkivum also provides an Archive Storage service for organisations with an [Open Archival Information System (OAIS)](https://en.wikipedia.org/wiki/Open_Archival_Information_System)

**Comment by Nimphal** [comment]
So based on that is there any reason why Willow couldn't use Arkivum as the main storage provider? Are the retrieval speeds going to be sufficient? If the answers is "probably not", then we can recommed using it as a backup solution due to that limitation.

**Comment by martyn-w** [comment]
Hi @Nimphal I've updated the analysis - see above and close this ticket if there are no further questions.

**Comment by richard-jones** [comment]
+1 - this is great, thanks
