### ISSUE TITLE
Edit button broken on willow.cottagelabs.com

### ISSUE THREAD

**Issue by martyn-w** [CottageLabs/willow#217]
When you login as a user and try to edit an existing object, the site throws an error.

**Comment by emanuil-tolev** [comment]
This should be reviewed again, @anusharanganathan has worked on it (or the periphery of it which might have fixed it)

**Comment by Nimphal** [comment]
This is not a problem is works have been uploaded after the latest workflow changes - the edit button no longer exists as users should not be allowed to Edit a work once it has been approved. Closing for now.
