### ISSUE TITLE
Notifications in workflows

### ISSUE THREAD

**Issue by anusharanganathan** [CottageLabs/willow#219]
In the current [mediated deposit workflow](https://github.com/CottageLabs/willow/blob/master/willow/config/workflows/mediated_deposit_workflow.json), the workflow based notifications (review, approve...) are seen by the depositing user but not by the approving user. 

In the workflow definition though, the notifications are to be sent to the approving user

Expected: Approving user and depositor receive notifications

**Comment by emanuil-tolev** [comment]
The RDSS are asking for an update on this. I will try to figure it out with @anusharanganathan when we're both available. Configuration appears to be correct so a little code dive might be necessary.

cc @Nimphal

**Comment by emanuil-tolev** [comment]
Another notification reported as not working:

> Comment added in Approval process is not notified to the depositor

**Comment by anusharanganathan** [comment]
The workflow based notifications is fixed in PR https://github.com/CottageLabs/willow/pull/244 to be visible to both depositor and approver as per the [definition in the mediated workflow](https://github.com/CottageLabs/willow/blob/bf22ee04778ba6bbeefc4d897bc01e5c09846aa8/willow/config/workflows/mediated_deposit_workflow.json). 

**_NOTE (for JISC)_** There is no email notification defined for comments as this is seen as something internal to the review process and not necessarily one for the depositor. It can be changed if an institution requires it, but this is clearly dependent on their use case and we would recommend leaving it as is for now.

**_A side note_** I tested notifications for comments by adding notifications for comments in the workflow and it did not work. So if we need this functionality we would need to look into why it is not working from within Hyrax and add a new issue

**Comment by Nimphal** [comment]
This has now been fixed.
