### ISSUE TITLE
Continuous integration and deployment of our docker setup to AWS

### ISSUE THREAD

**Issue by Nimphal** [CottageLabs/willow#3]
- [ ] CI & CD for production

  different docker cloud files, or different branches in the willow repo will trigger deploys

- [ ] CI & CD for staging

  - on-demand (cost)
  - syphon off all current production data and anonymise it, then import into staging
  - run newest code for this customer (from a branch or whatever)

- [ ] CI for test (i.e. github) and CD to our demo site

**Comment by emanuil-tolev** [comment]
Docker Cloud offers something related to continuous integration, check it out

**Comment by emanuil-tolev** [comment]
$15 for Docker Cloud, $40 for a DO demo machine.

**Comment by Nimphal** [comment]
From the docker-compose documentation https://docs.docker.com/compose/production/#/running-compose-on-a-single-server

**Comment by Nimphal** [comment]
Considering we would like to as close to AWS infrastructure, Docker Cloud seems like the best option. It will manage, build and run tests for us: https://docs.docker.com/docker-cloud/builds/automated-testing/
We would need to convert our docker-compose.yml to a docker-cloud.yml following https://docs.docker.com/docker-cloud/apps/stack-yaml-reference/ . 

Docker cloud is $15 per node. AWS for a `t2.medium` (2 vCPUs, 4 GB RAM) is roughly $40.88 per month on demand, $29.20 for a reserved instance with no upfront payment.

Altogether, the price for a Docker Cloud managed, AWS hosted demo service is between $45 and $56. per month, depending on what we commit to.

**Comment by emanuil-tolev** [comment]
I'd go for reserved with full upfront payment, the reserved no upfront still commits you for at least a year, so you have to hand over the money within the year anyway. What's the cost of fully upfront prepaid medium?

**Comment by Nimphal** [comment]
Yearly $326, effectively $27.17 a month.

**Comment by emanuil-tolev** [comment]
Oh alright then, we can go for no upfront payment reserved.

However, at first, let's deploy just on an on-demand (more expensive) instance. We need to finalise the setup and know how much CPU and RAM we need for a very basic version with say ~10-20 users, i.e. a running demo.

**Comment by emanuil-tolev** [comment]
- [x] Fedora works on Docker Cloud
- [x] Postgres is persisted on Docker Cloud
- [ ] Fedora is persisted as well (?)
- [ ] Solr is persisted (atm it's definitely not, wrong volume directory on the container)

**Comment by Nimphal** [comment]
All the goals of this issue have now been achieved, any further work on this will happen in new issues.
