### ISSUE TITLE
Seed data on vanilla willow platform start-up

### ISSUE THREAD

**Issue by emanuil-tolev** [CottageLabs/willow#32]
Possibly import an export that was made manually out of the vagrant hacky box we used to have.

Also this should include appropriate admin accounts. For now it's ok for these to be part of the export, but in the future they might need to be separated in a separate rerunnable script to make it easier to add new admins or change their data.

The seeds must not be used when deploying to production or staging.

**Comment by Nimphal** [comment]
This has been done, closing.

**Comment by martyn-w** [comment]
Actually there are some outstanding issues with this, specifically:
* Noid minter ids are not preserved
* redis data should be preserved (as it records the audit log on objects)
* thumbnails are missing for some types of objects
I'm currently working on all of the above

**Comment by Nimphal** [comment]
There is a thumbnails issue #118 , could you create issues for the other two things? This issue was to do the initial work, and we can monitor problems with it in separate issues.

**Comment by Nimphal** [comment]
Issue for redit data #123 

Is the noid issue behind our data woes? If so there probably is an issue about it already, but I don't understand enough to decide.

**Comment by Nimphal** [comment]
Hey @martyn-w has this been resolved by #129 and #130 ?

**Comment by martyn-w** [comment]
yep, this can be closed
