### ISSUE TITLE
ADFS compatibility

### ISSUE THREAD

**Issue by Nimphal** [CottageLabs/willow#62]
Investigate what's needed to allow users to login into Willow via ADFS assuming Willow is not hosted on premises.

**Comment by emanuil-tolev** [comment]
This will be very hard to test as AD FS itself requires IIS (Microsoft's web server) and a whole bunch of configuration to run. We don't have to run it in Willow in order to support AD FS, but we also have no test system for it - our first integration will be the test. Hopefully whoever we integrate with will be able to provide a suitable test AD FS instance.

**Comment by emanuil-tolev** [comment]
In terms of supporting it, some development work needs to happen. When authenticating a user, we would have to provide an option to use AD FS, or replace the username+password form with an AD FS box.

On the implementation, AD FS is quite similar to OAuth2. It can use various protocols (unfortunately not OAuth2) to do the authentication. A lot depends on how the remote AD FS server is configured. Generally, the SAML protocol is supported in AD FS (as long as our integration partner has not disabled it - but there's generally no reason to do so). There's also WS-Fed, which also appears to use SAML underneath.

In that case this issue boils down to implementing WS-Fed or direct SAML authentication in Ruby. http://stackoverflow.com/q/30314255/1154882 has general information on supporting AD FS in Ruby.

https://blog.craig.io/using-microsoft-adfs-with-ruby-on-rails-and-omniauth-a26237c64f8d#.sv5qke1hx is a blog post on how somebody integrated a rails app with their university's AD FS server ;). They used omniauth with budding WS-Fed support successfully and provide lots of valuable information. Here's an internet archive backup in case the blog goes down: http://web.archive.org/save/_embed/https://blog.craig.io/using-microsoft-adfs-with-ruby-on-rails-and-omniauth-a26237c64f8d?gi=33f3a45cd766 . I have also asked a successful implementer of ADFS 3.0 with the ruby-saml gem for more information on how they did it: https://github.com/onelogin/ruby-saml/issues/276

Recap:

- follow that blog post to use WS-Fed
- try to use the onelogin/ruby-saml gem

Either way, we can put in some theoretical support, but the only way to be sure will be to have access to an AD FS instance that is configured to trust our demo app.

**Comment by Nimphal** [comment]
Let me just recap so I'm sure I understand correctly.

ADFS is definitely something we can do. It will require the client to provide us with the correct testing environment and credentials, after which we can choose an approach and try to implement it. Unless there are some specific changes in the way ADFS is implemented on the client side, it should be possible for us to implement.

If the above is correct I am happy to close the issue. FYI @richard-jones

**Comment by emanuil-tolev** [comment]
Yes, in brief we support ADFS. Everything you say is correct.

We now have two strong leads on two approaches to implementing it. One via a detailed and recent blog post, and one via an example on github that I asked for. My updated comment above should be enough to get started when we have an AD FS instance on the client side to test against.

In the ideal case it would take a few hours to implement. Realistically (with configuration problems) it will take a few or several days with us being blocked by asking the client questions about their AD FS setup.

**Comment by emanuil-tolev** [comment]
"ADFS" stands for Active Directory Federation Services. Techies often abbreviate it to "AD FS", others omit the space.

**Comment by markmacgillivray** [comment]
I've integrated python and bash auth to adfs before. Don't underestimate
how long it will take for procedure-oriented IT depts to allow your scripts
to interact with their adfs. Some may be fine and do it in a few days, but
waiting months would not be surprising.

**Comment by emanuil-tolev** [comment]
> I've integrated python and bash auth to adfs before. Don't underestimate
> how long it will take for procedure-oriented IT depts to allow your scripts
> to interact with their adfs. Some may be fine and do it in a few days, but
> waiting months would not be surprising.

Are those integrations on some of the recent projects on github?

Thanks for the heads-up. What you describe seems like it's become (or always was) a pattern with all single sign on systems we've come across.

**Comment by markmacgillivray** [comment]
No, this was pre-CL, nothing public we can re-use. I was more just pointing
out the possibility of long delay, and to make that clear when discussing
with clients, as it happened when i was doing that kind of work.

Also if you happen to get into more adfs complexities, (beyond just auth
integrations) i do know an adfs expert consultant i can put you in touch
with.

**Comment by Nimphal** [comment]
Thank you both, closing this now :)
