### ISSUE TITLE
SWORDv2 server

### ISSUE THREAD

**Issue by Nimphal** [CottageLabs/willow#7]
Expose a SWORDv2 end point in Willow.

**Comment by Nimphal** [comment]
@martyn-w would it be okay if I close this, as we now have the skeleton in place? Any further enhancements will be tracked in new issues.

**Comment by martyn-w** [comment]
Hi @Nimphal, yes, on the understanding that this work is very far from complete

**Comment by Nimphal** [comment]
Would it be possible to get a list of what's needed to complete the work? While it's still sort of fresh in your mind :)

**Comment by martyn-w** [comment]
Hi @Nimphal, ultimately we need to implement all the methods/endpoints defined in http://swordapp.github.io/SWORDv2-Profile/SWORDProfile.html

Currently only the **Service Document IRI** is partially implemented - which is around 10-20% of this issue.

**Comment by Nimphal** [comment]
Thank you, I will take care of noting down the rest in an epic :) Closing this now.
