### ISSUE TITLE
Willow data model for deposit tool

### ISSUE THREAD

**Issue by Nimphal** [CottageLabs/willow#78]

**Comment by anusharanganathan** [comment]
Bagit format. Metadata similar to Cambridge. Should be configurable if we save entire bag or just the data and metadata

**Comment by anusharanganathan** [comment]
Need to be able to discover, view and edit administrative privileges

**Comment by anusharanganathan** [comment]
@Nimphal this is now superseded by #139

**Comment by Nimphal** [comment]
Is there any more work to be done as part of this issue or is it taken care of by #138 and #139 ?

**Comment by anusharanganathan** [comment]
This is done. It is covered by https://github.com/CottageLabs/willow/pull/161, https://github.com/CottageLabs/willow/pull/172 and https://github.com/CottageLabs/willow/issues/151 
It is taken over by #139.

**Comment by Nimphal** [comment]
Perfect, closing.
