### ISSUE TITLE
When running any demo, run all software in production, not development

### ISSUE THREAD

**Issue by emanuil-tolev** [CottageLabs/willow#85]

**Comment by martyn-w** [comment]
Hi @emanuil-tolev, are you sure about this? Sometimes it is useful to develop in development mode rather than in production mode. Perhaps we need a toggle switch to be able to select the mode?

**Comment by emanuil-tolev** [comment]
> Hi @emanuil-tolev, are you sure about this? Sometimes it is useful to develop in development mode rather than in production mode. Perhaps we need a toggle switch to be able to select the mode?

Absolutely, I meant "run the demo in production mode". Devs continue to use dev mode.

**Comment by Nimphal** [comment]
We do have running demo, so this issue isn't currently relevant, closing.
