### ISSUE TITLE
Clean up large files from willow repository

### ISSUE THREAD

**Issue by emanuil-tolev** [CottageLabs/willow#89]
The repo is over 170 megabytes at the moment. This can make automated rebuilds slower. Sometimes it makes pushing and pulling slower. Finally, obviously if you try to re-clone it on a train you'll be in trouble.

```
emanuil@midori:~/cl/willow$ ./git_find_big.sh 
All sizes are in kB's. The pack column is the size of the object, compressed, inside the pack file.
size   pack   SHA                                       location
64497  64512  3bd536a10ff8ee2158b106f7d732fdf1b9ec65ba  fedora_commons/example_willow_objects.tar.gz
64496  64512  46de2a730cf6b1585719995628b668f7fd332f3d  fedora_commons/example_willow_objects.tar.gz
45472  45469  6896a6dc5820eef00ef12da697233a7023667a7d  fedora_commons/fcrepo-webapp-4.6.1.war
523    466    6dbdac0f66cf2895a1e21d27bba72e962f543c19  willow/app/assets/images/cottage_hill_banner.png
388    387    51695ffcf69c3c144497e9fde857fff6dfe8f095  willow/app/assets/images/willow5.jpg
230    229    b2427d9f8c1e4a5e8c8fd00da2355a00bf433cf9  docs/images/willow.png
155    23     eee603dd4711955f5b05728bee62644223dbc968  willow/solr/sample_solr_documents.yml
113    112    08dd77bf0e30b3f679c3cf477c46ed0b38598fc0  docs/images/fedora.png
33     8      62c895e5d644f2c9f718c151454208ca9301d6be  willow/solr/conf/schema.xml
21     4      2e9deac632585c54e782c3125a7a8e79eaed28ea  willow/solr/config/schema.xml
```
(Here is the script that produced this output: https://gist.github.com/emanuil-tolev/d531e25b9e1a9dd493701dc254c97e55 )

EDIT:

Some more to delete:
- `willow/public/system/avatars/1/medium/IMG_20170213_104509_023.jpg`
- `willow/public/system/avatars/1/original/IMG_20170213_104509_023.jpg`
- `willow/public/system/avatars/1/thumb/IMG_20170213_104509_023.jpg`

Store binary files on AWS S3 and pull them in as required. I'd suggest moving `fedora_commons/fcrepo-webapp-4.6.1.war` and `fedora_commons/example_willow_objects.tar.gz` to S3.

The files need to then be deleted from the git history. This will rewrite the history of the master branch, and will necessitate that everybody re-clones the repository. Not just pulls master - that will actually have the effect of putting the bad files back in. Instead, **once the repo has been cleaned with the BFG** we will all need to:

1. go into the willow repository locally
2. mv .env /tmp/willow-env
3. mv .idea /tmp/willow-idea  # if .idea exists for you
4. cd ..
5. rm -rf willow
6. git clone git@github.com:CottageLabs/willow.git
7. mv /tmp/willow-env .env
8. mv /tmp/willow-idea .idea  # if you have an .idea folder

**We should only do this once the repo has been cleaned with the BFG. Probably during a face to face or online meeting.**

The BFG repo cleaner: https://rtyley.github.io/bfg-repo-cleaner/

**Comment by martyn-w** [comment]
Hmmm, I'm not sure about the logic here: 
* In order to run Willow, you will need some big files (e.g. example data archive, fedora installation files, docker base images etc). 
* Regardless of where these files exist/persist (e.g. on git, on S3, on Dockerhub, over a rainbow etc), you will need them locally in order to run Willow locally.
* So, what is to be gained by moving them out of git and into say S3?

**Comment by emanuil-tolev** [comment]
Git re-stores the entire file every time you change it. If you put a 45MB file in, and change it once, now it takes up 90MB. Change it another time, the repo is now 135MB. Change it again, it's ... you get the idea. It makes the repository hard to clone and puts in a large delay where it needs to be cloned from scratch, like continuous integration systems such as codeship or Docker Cloud.

**Comment by martyn-w** [comment]
ok sounds reasonable 👍

**Comment by martyn-w** [comment]
Sorry for adding these large files. I'm currently working on a branch (`improve_fedora`) to resolve some Fedora stability issues and whilst I am at it, I have removed the two large files. Once this is merged back to master, we can organise deleting the git history.

**Comment by emanuil-tolev** [comment]
Some more unnecessary files were just added with the Sufia 7.3 upgrade. Nev is working on .gitignoring such files in the future.

3 image files added to list above.

**Comment by emanuil-tolev** [comment]
Best done in a meeting together, or in individual meetings. Otherwise people's local copy of master (and any other branches that had the large files) will make it back into the repo pretty quickly.

**Comment by emanuil-tolev** [comment]
What I did to clean up

```bash
cd cl/willow
# back up my .idea and .env folders as per instructions above
cd ..
rm -rf willow
git clone --mirror git://github.com/CottageLabs/willow.git
cd willow.git
java -jar ~/software/bfg-1.12.15.jar  # see the help
java -jar ~/software/bfg-1.12.15.jar --strip-blobs-bigger-than 10M .
git reflog expire --expire=now --all && git gc --prune=now --aggressive
java -jar ~/software/bfg-1.12.15.jar --delete-files IMG_20170213_104509_023.jpg
git reflog expire --expire=now --all && git gc --prune=now --aggressive
```

**Comment by emanuil-tolev** [comment]
@martyn-w @Nimphal @anusharanganathan please delete and re-clone the Willow repository *on all machines* where you have it cloned. See the bottom of https://github.com/CottageLabs/willow/issues/89#issue-212142263 for explicit instructions if you need.

**Comment by emanuil-tolev** [comment]
We now all need to:

    # cd local_willow_dir
    mv .env /tmp/willow-env
    mv .idea /tmp/willow-idea # if .idea exists for you
    cd ..
    rm -rf willow
    git clone git@github.com:CottageLabs/willow.git
    mv /tmp/willow-env .env
    mv /tmp/willow-idea .idea # if you have an .idea folder

**Comment by Nimphal** [comment]
Closing this down as the work has been done.

**Comment by emanuil-tolev** [comment]
Afraid the test server needs updating as well, but I will close this when *that* is done.
