### ISSUE TITLE
startup_prod.sh fedora health check is not suited for production

### ISSUE THREAD

**Issue by emanuil-tolev** [CottageLabs/willow#93]
```
FEDORA=$(curl --silent --connect-timeout 30 "http://fedora:8080/fcrepo/" | grep "Fedora Commons Repository")
```
This doesn't seem to work, specifically host resolution of `fedora` doesn't work. It does appear to work from inside Ruby - e.g. `db` definitely used to simply work as a database hostname when we had a running Willow demo.

However, using these hostnames from bash doesn't seem to work - `ping db` doesn't work, for example. And yet, the old rails v4 app certainly did connect to postgres using hostname specified as simply `db`.

EDIT: this does work with docker-compose locally in development.

**Comment by martyn-w** [comment]
are you running within docker-compose? and is the host (fedora) a linked server?

**Comment by martyn-w** [comment]
ah I see this fails on production :-( boo

**Comment by Nimphal** [comment]
As agreed in meeting, we're moving away from Docker Cloud, so this issue is not relevant right now. Closing.
